config/routes.rb
Agora::Application.routes.draw do
  root 'snippets#index'

  resources :users,         only: [:create, :destroy, :show]
  resources :sessions,      only: [:create, :destroy]
  resources :languages,     only: [:index, :show]
  resources :comments,      only: [:create]
  resources :notifications, only: [:update]
  resources :snippets

  get '/signup',  to: "users#new",        as: 'sign_up'
  get '/signin',  to: "sessions#new",     as: 'sign_in'
  get '/signout', to: "sessions#destroy", as: 'sign_out'

  get "/auth/:provider/callback" => "sessions#github_login"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ApplicationHelper

  belongs_to :snippet
  belongs_to :user

  validates_presence_of :user, :snippet
  validates :content, presence: true

  after_create :notify_snippet_creator

  def pretty_content
    markdown content
  end

  def notify_snippet_creator
    message = "#{user.username} has posted a comment on your snippet #{snippet.name}."
    snippet.user.notify(message)
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :snippets

  def to_pygments
    {
      'Bash' => 'sh',
      'C++' => 'cpp',
      'Assembly' => 'gas'
    }[name] || name.downcase
  end

  def pretty_description
    require 'pygmentize'
    Pygmentize.process(description, to_pygments)
  end

  def to_param
    name
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user

  CONFIRMATION_DIALOGS = [
    "Sweet",
    "Awesome",
    "Fantastic",
    "They're the best",
    "Stupendous",
    "Marvelous",
    "Fabulous"
  ]
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  include ApplicationHelper

  validates :name, :content, presence: true
  validates :permalink, presence: true, uniqueness: true
  validates_presence_of :language

  belongs_to :user
  belongs_to :language
  has_many   :comments

  before_validation :assign_permalink
  before_validation :assign_name, if: proc { |s| s.name.blank? }

  default_scope -> { where public: true }
  default_scope -> { order 'created_at DESC' }

  def to_param
    permalink
  end

  def pretty_content
    require 'pygmentize'
    Pygmentize.process(content, language.to_pygments)
  end

  private

  def assign_permalink
    self.permalink = SecureRandom.hex(7)
  end

  def assign_name
    self.name = unique_name_for content, user.username
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :snippets
  has_many :comments
  has_many :notifications

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true,
                    presence: true,
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }

  before_save { self.email = email.downcase }

  def self.find_or_create_by_omniauth(auth)
    user = User.find_by_email(auth['info']['email'])

    unless user
      new_password = SecureRandom.hex(16)
      user = {
        username: auth['info']['nickname'],
        email: auth['info']['email'],
        password: new_password,
        password_confirmation: new_password
      }
      user = create! user
    end

    user
  end

  def unread_notifications
    notifications.where(unread: true)
  end

  def to_param
    username
  end

  def notify(content)
    notifications.create content: content
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    fail ActionController::RoutingError, 'Not Found'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new comment_params
    if @comment.save
      head :no_content
    else
      render json: @comment.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :snippet_id)
  end
end

app/controllers/languages_controller.rb
# Languages are only created and updated through seeds or the console itself.
class LanguagesController < ApplicationController
  def index
    @languages = Language.all.order(:name)
  end

  def show
    @language = Language.find_by_name params[:id]
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :set_notification

  def update
    if @notification.update notification_params
      head :ok
    else
      head :unprocessable_entity
    end
  end

  private
    def set_notification
      @notification = Notification.find(params[:id])

      unless signed_in? && current_user == @notification.user
        head :unauthorized
      end
    end

    def notification_params
      params.require(:notification).permit(:unread)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      flash.now[:error] = "You're already signed in."
      redirect_to root_url
    end
  end

  def create
    user = User.find_by_username params[:session][:username]
    if user && user.authenticate(params[:session][:password])
      flash[:notice] = 'Welcome back.'
      sign_in user
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid username/password combination'
      render :new
    end
  end

  def github_login
    auth = request.env['omniauth.auth']
    user = User.find_or_create_by_omniauth(auth)
    flash[:notice] = 'Welcome back.'
    sign_in user
    redirect_to :back
  end

  def destroy
    sign_out
    redirect_to :root
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_filter :signed_in,    except: [:index, :show]
  before_filter :set_snippet,  only:   [:show, :edit, :update, :destroy]
  before_filter :correct_user, only:   [:edit, :update, :destroy]

  def index
    @snippets = Snippet.all
  end

  def show
  end

  def edit
  end

  def new
    @snippet = Snippet.new
  end

  def update
    if @snippet.update snippet_params
      flash[:notice] = 'Snippet updated.'
      redirect_to @snippet
    else
      render :edit
    end
  end

  def create
    @snippet = current_user.snippets.new snippet_params
    if @snippet.save
      flash[:notice] = 'Snippet created.'
      redirect_to @snippet
    else
      render :new
    end
  end

  def destroy
    @snippet.destroy
    flash[:notice] = 'Snippet deleted.'
    redirect_to :snippets
  end

  private

  def snippet_params
    params.require(:snippet).permit(%i(
      name content permalink language_id description public
    ))
  end

  def set_snippet
    @snippet   = Snippet.find_by_permalink(params[:id])
    @snippet ||= Snippet.find_by_permalink_and_public(params[:id], false)
    not_found unless @snippet
  end

  def signed_in
    unless signed_in?
      flash[:error] = 'You must sign in to access that page'
      redirect_to :root
    end
  end

  def correct_user
    snippet = current_user.snippets.unscoped.find_by_permalink(params[:id])
    redirect_to :root if snippet.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Welcome to Agora.'
      sign_in @user
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find_by_username params[:id]
  end

  private

  def user_params
    params.require(:user).permit(%i(
      username password password_confirmation email
    ))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in?
    session[:current_user_id].present?
  end

  def sign_in(user)
    session[:current_user_id] = user.id
  end

  def sign_out
    session[:current_user_id] = nil
  end

  def current_user
    session[:current_user_id] && User.find(session[:current_user_id])
  end

  def unique_name_for(*args)
    require 'digest/sha1'
    Digest::SHA1.hexdigest(args.join)[0..10]
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: 'gravatar')
  end

  def markdown(string)
    require 'rdiscount'
    RDiscount.new(string).to_html
  end
end

app/views/comments/_comment.haml
.comment-box
  = gravatar_for comment.user
  %h4= link_to comment.user.username, comment.user
  = raw comment.pretty_content

app/views/comments/_form.haml
%form.new-comment{data: {id: snippet_id}}
  .form-group
    %textarea.content{placeholder: 'Markdown Supported.'}
  .form-group
    %a.blue.button.comment-submit Submit

app/views/languages/_language.haml
- snippet_count = language.snippets.count
.language-box
  %h3
    = link_to language.name, language
    %span{style: "float: right; color: #aaa"} #{snippet_count} #{"Snippet".pluralize(snippet_count)}
  = preserve raw language.pretty_description

app/views/languages/index.haml
.row.clearfix
  .container
    %h2 All Languages

.row.clearfix
  .container
    = render @languages

app/views/languages/show.haml
.row.clearfix
  .container
    %h2 #{@language.name} Snippets

.row.clearfix
  .container
    = render partial: 'snippets/snippet', collection: @language.snippets, as: 'snippet'

app/views/layouts/_header.haml
- if signed_in?
  .navbar.clearfix
    .column.half
      %p
        = link_to "Snippets", snippets_path
        = link_to "Languages", languages_path
        = link_to "Sign Out", sign_out_path, via: :delete
    .column.half.nav
      %p
        = link_to "Your Snippets", current_user
        = link_to "Create a Snippet", new_snippet_path, class: 'clear-button'
        .floating-gravatar= gravatar_for current_user
- else
  .hero.clearfix
    .container
      %h1.logo= link_to "Agora", root_url
      %p We're making sharing code easier than ever before.
      %p= link_to "Sign In with GitHub", "/auth/github", class: 'clear-button github-link'
      %p.small= link_to 'Use Your Email Instead', sign_up_url

app/views/layouts/application.haml
!!!
%html
  %head
    %title Agora
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %link{:href => image_url('favicon.ico'), :rel => 'icon', :type => 'image/x-icon'}
    = stylesheet_link_tag "//brick.a.ssl.fastly.net/Source+Sans+Pro:400,600/Source+Code+Pro:400"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Oswald:400"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - if flash.any?
      - flash.each do |key, value|
        .clearfix{:class => "alert #{key}"}
          .container
            %strong= value
    - if signed_in? && current_user.unread_notifications.any?
      = render current_user.unread_notifications

    = yield

    = render 'layouts/tracking'

app/views/notifications/_notification.haml
.row.clearfix.alert.notification
  .container
    %p
      %strong= notification.content
    %a.blue.button.mark-as-read{data: { id: notification.id }}
      %strong= Notification::CONFIRMATION_DIALOGS.sample

app/views/snippets/_form.haml
= form_for @snippet do |f|
  .form-group
    = f.label :name
    = f.text_field :name, placeholder: 'Optional'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'text', placeholder: 'Optional'
  .form-group
    = f.label :language
    = f.collection_select :language_id, Language.all, :id, :name
  .form-group
    = f.label :content
    = f.text_area :content, class: 'code'
  .form-group
    %p Private snippets are only visible to those with a link to them.
    = f.button "Make it Public",  type: 'submit', name: 'snippet[public]', value: 1, class: 'blue button'
    = f.button "Make it Private", type: 'submit', name: 'snippet[public]', value: 0, class: 'green button'

app/views/snippets/_snippet.haml
.snippet-box
  %h3
    %span.username= link_to snippet.user.username, snippet.user
    = '/'
    = link_to snippet.name, snippet
  %p.details
    #{time_ago_in_words(snippet.created_at)} ago
    - unless snippet.public?
      ·
      %span.private Private
    · #{snippet.comments.count} Comments
  %p= snippet.description
  = preserve raw snippet.pretty_content
%hr

app/views/snippets/edit.haml
.row.clearfix
  .container
    %h2 Update #{@snippet.name}

- if @snippet.errors.any?
  .row.clearfix
    .container
      %p
        %strong Check Yourself.
      %ul
        - @snippet.errors.full_messages.each do |message|
          %li= message

.row.clearfix
  .container
    = render 'form'

app/views/snippets/index.haml
.row.clearfix
  .container
    %h2 Newest Snippets

.row.clearfix
  .container
    = render @snippets

app/views/snippets/new.haml
.row.clearfix
  .container
    %h2 Create a Snippet

- if @snippet.errors.any?
  .row.clearfix
    .container
      %p
        %strong Check Yourself.
      %ul
        - @snippet.errors.full_messages.each do |message|
          %li= message

.row.clearfix
  .container
    = render 'form'

app/views/snippets/show.haml
.snippet-page

  .row.clearfix
    .container
      %h2
        %span.username= link_to @snippet.user.username, @snippet.user
        = '/'
        = @snippet.name

      %p.details
        #{time_ago_in_words(@snippet.created_at)} ago
        - unless @snippet.public?
          ·
          %span.private Private

      - if signed_in? && @snippet.user == current_user
        %p
          = link_to 'Delete', @snippet, method: 'delete', class: 'red button'
          = link_to 'Edit', edit_snippet_path(@snippet), class: 'green button'

      %p
        %strong= @snippet.language.name
        = "― #{@snippet.description}" unless @snippet.description.blank?

  .row.clearfix
    .container
      %table.code-table
        %tr
          %td.code
            - 1.upto(@snippet.content.split("\n").length) do |n|
              %a{name: n, href: "##{n}"}= n
              %br
          %td
            = preserve raw @snippet.pretty_content

  - if @snippet.comments.any?
    .row.clearfix
      .container
        %h3 Comments
        = render @snippet.comments

  - if signed_in?
    .row.clearfix
      .container
        %h3 Make a Comment
        = render 'comments/form', snippet_id: @snippet.id
  - else
    .row.clearfix
      .container
        %h3 Sign in to leave a comment.

app/views/users/new.haml
.row.clearfix
  .container
    %h2 Create an Account

- if @user.errors.any?
  .row.clearfix
    .container
      %p
        %strong Check Yourself.
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

.row.clearfix
  .container
    = form_for @user do |f|
      .form-group
        = f.label :username
        = f.text_field :username
      .form-group
        = f.label :email
        = f.email_field :email
      .form-group
        = f.label :password
        = f.password_field :password
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation
      .form-group
        = f.submit "Create Account"

app/views/users/show.haml
.row.clearfix
  .container
    %h2 #{@user.username}'s Snippets

.row.clearfix
  .container
    - if signed_in? && current_user == @user
      = render @user.snippets.where(public: [true, false])
    - else
      = render @user.snippets